name: Deploy lab3
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci && npm run build
        env:
          VITE_HASURA_ADMIN: '${{ secrets.VITE_HASURA_ADMIN }}'
          VITE_API_HTTPS_ENDPOINT: '${{ secrets.VITE_API_HTTPS_ENDPOINT }}'
          VITE_API_WSS_ENDPOINT: '${{ secrets.VITE_API_WSS_ENDPOINT }}'
        working-directory: lab3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_LAB3 }}'
          projectId: newtwiter-ca45b
          entryPoint: ./lab3
